name:                composite-swagger
version:             0.5.5.0
synopsis:            Swagger for Vinyl/Frames records
description:         Integration between Swagger and Vinyl/Frames records allowing easily derivable/explicit Swagger definitions for records.
homepage:            https://github.com/ConferHealth/composite#readme
license:             BSD3
author:              Confer Health, Inc
maintainer:          oss@confer.health
copyright:           2017 Confer Health, Inc.
category:            Records

dependencies:
  - base >= 4.7 && < 5
  - composite-base >= 0.5.3.0 && < 0.6
  - insert-ordered-containers >= 0.2.1.0 && < 0.3
  - lens >= 4.15.4 && < 4.18
  - swagger2 >= 2.1.6 && < 2.4
  - template-haskell >= 2.11.1.0 && < 2.15
  - text >= 1.2.2.2 && < 1.3
  - vinyl >= 0.5.3 && < 0.9

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - PolyKinds
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src

tests:
  composite-swagger-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans
    dependencies:
      - QuickCheck
      - composite-aeson
      - composite-base
      - composite-swagger
      - hspec
